### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by elizabetdev** [Modulr/angular-file#13]
The plugins works well but everytime I drop a file I see this error on **chrome console**:

```
SyntaxError: Unexpected token <
    at Object.parse (native)
    at http://localhost/app/bower_components/mdr-angular-file/dist/mdr-file.js:220:31
    at Scope.$eval (http://localhost/app/bower_components/angular/angular.js:16052:28)
    at Scope.$apply (http://localhost/app/bower_components/angular/angular.js:16152:25)
    at XMLHttpRequest.transferComplete (http://localhost/app/bower_components/mdr-angular-file/dist/mdr-file.js:218:16)
```

Error on **firefox console**:

```
Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
transferComplete/<@http://localhost/app/bower_components/mdr-angular-file/dist/mdr-file.js:220:26
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost/app/bower_components/angular/angular.js:16052:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost/app/bower_components/angular/angular.js:16152:20
transferComplete@http://localhost/app/bower_components/mdr-angular-file/dist/mdr-file.js:218:9
```

I'm running my app with `Angular 1.4.8`

**Comment by alfredobarron** [comment]
Thanks for comments @miukimiu I will review

**Comment by alfredobarron** [comment]
This error is generated because the server response must be of type JSON.
